spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
    data-password: 1234
  jpa:
    hibernate:
      ddl-auto: update

---

#spring:
#  profiles:
#    active: test
#  datasource:
#    url: jdbc:h2:mem:test
