spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
    driver-class-name: org.h2.Driver
    data-username: sa
    data-password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

jwt:
  secret: 12345678901234567890123456789012
---

#spring:
#  profiles:
#    active: test
#  datasource:
#    url: jdbc:h2:mem:test
