spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
    data-password: 1234
    driver-class-name: org.h2.Driver
    data-username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

---

#spring:
#  profiles:
#    active: test
#  datasource:
#    url: jdbc:h2:mem:test
